from PyQt5 import QtCore, QtGui, QtWidgets
import datetime
import os

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.roomprops = QtWidgets.QTextBrowser(self.centralwidget)
        self.roomprops.setObjectName("roomprops")
        self.gridLayout.addWidget(self.roomprops, 1, 1, 1, 1)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.text_name = QtWidgets.QLabel(self.centralwidget)
        self.text_name.setObjectName("text_name")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.text_name)
        self.in_name = QtWidgets.QLineEdit(self.centralwidget)
        self.in_name.setObjectName("in_name")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.in_name)
        self.text_lastname = QtWidgets.QLabel(self.centralwidget)
        self.text_lastname.setObjectName("text_lastname")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.text_lastname)
        self.in_lastname = QtWidgets.QLineEdit(self.centralwidget)
        self.in_lastname.setObjectName("in_lastname")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.in_lastname)
        self.text_middlename = QtWidgets.QLabel(self.centralwidget)
        self.text_middlename.setObjectName("text_middlename")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.text_middlename)
        self.in_middlename = QtWidgets.QLineEdit(self.centralwidget)
        self.in_middlename.setObjectName("in_middlename")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.in_middlename)
        self.text_mobilenum = QtWidgets.QLabel(self.centralwidget)
        self.text_mobilenum.setObjectName("text_mobilenum")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.text_mobilenum)
        self.in_mobilenum = QtWidgets.QLineEdit(self.centralwidget)
        self.in_mobilenum.setObjectName("in_mobilenum")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.in_mobilenum)
        self.text_datein = QtWidgets.QLabel(self.centralwidget)
        self.text_datein.setObjectName("text_datein")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.text_datein)
        self.in_datein = QtWidgets.QDateEdit(self.centralwidget)
        self.in_datein.setObjectName("in_datein")
        self.in_datein.setDate(datetime.date.today())
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.in_datein)
        self.text_roomsnum = QtWidgets.QLabel(self.centralwidget)
        self.text_roomsnum.setObjectName("text_roomsnum")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.text_roomsnum)
        self.in_roomsnum = QtWidgets.QSpinBox(self.centralwidget)
        self.in_roomsnum.setObjectName("in_roomsnum")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.in_roomsnum)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.text_hastv = QtWidgets.QLabel(self.centralwidget)
        self.text_hastv.setObjectName("text_hastv")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.text_hastv)
        self.in_hastv = QtWidgets.QCheckBox(self.centralwidget)
        self.in_hastv.setText("")
        self.in_hastv.setObjectName("in_hastv")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.in_hastv)
        self.text_haswifi = QtWidgets.QLabel(self.centralwidget)
        self.text_haswifi.setObjectName("text_haswifi")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.text_haswifi)
        self.in_haswifi = QtWidgets.QCheckBox(self.centralwidget)
        self.in_haswifi.setText("")
        self.in_haswifi.setObjectName("in_haswifi")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.in_haswifi)
        self.text_hassafe = QtWidgets.QLabel(self.centralwidget)
        self.text_hassafe.setObjectName("text_hassafe")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.text_hassafe)
        self.in_hassafe = QtWidgets.QCheckBox(self.centralwidget)
        self.in_hassafe.setText("")
        self.in_hassafe.setObjectName("in_hassafe")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.in_hassafe)
        self.formLayout_4.setLayout(7, QtWidgets.QFormLayout.LabelRole, self.formLayout_5)
        self.formLayout_9 = QtWidgets.QFormLayout()
        self.formLayout_9.setObjectName("formLayout_9")
        self.text_haspets = QtWidgets.QLabel(self.centralwidget)
        self.text_haspets.setObjectName("text_haspets")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.text_haspets)
        self.in_haspets = QtWidgets.QCheckBox(self.centralwidget)
        self.in_haspets.setText("")
        self.in_haspets.setObjectName("in_haspets")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.in_haspets)
        self.text_smoker = QtWidgets.QLabel(self.centralwidget)
        self.text_smoker.setObjectName("text_smoker")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.text_smoker)
        self.in_smoker = QtWidgets.QCheckBox(self.centralwidget)
        self.in_smoker.setText("")
        self.in_smoker.setObjectName("in_smoker")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.in_smoker)
        self.text_hasbreakfast = QtWidgets.QLabel(self.centralwidget)
        self.text_hasbreakfast.setObjectName("text_hasbreakfast")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.text_hasbreakfast)
        self.in_hasbreakfast = QtWidgets.QCheckBox(self.centralwidget)
        self.in_hasbreakfast.setText("")
        self.in_hasbreakfast.setObjectName("in_hasbreakfast")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.in_hasbreakfast)
        self.formLayout_4.setLayout(7, QtWidgets.QFormLayout.FieldRole, self.formLayout_9)
        self.text_dateout = QtWidgets.QLabel(self.centralwidget)
        self.text_dateout.setObjectName("text_dateout")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.text_dateout)
        self.in_dateout = QtWidgets.QDateEdit(self.centralwidget)
        self.in_dateout.setObjectName("in_dateout")
        self.in_dateout.setDate(datetime.date.today())
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.in_dateout)
        self.gridLayout.addLayout(self.formLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.BtnSearch = QtWidgets.QPushButton(self.centralwidget)
        self.BtnSearch.setObjectName("BtnSearch")
        self.horizontalLayout_4.addWidget(self.BtnSearch)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BtnReservate = QtWidgets.QPushButton(self.centralwidget)
        self.BtnReservate.setObjectName("BtnReservate")
        self.horizontalLayout_2.addWidget(self.BtnReservate)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ListRooms = QtWidgets.QListWidget(self.centralwidget)
        self.ListRooms.setObjectName("ListRooms")
        self.horizontalLayout.addWidget(self.ListRooms)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.calendar = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendar.setObjectName("calendar")
        self.calendar.setSelectionMode(QtWidgets.QCalendarWidget.SelectionMode.NoSelection)
        self.gridLayout.addWidget(self.calendar, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        scriptDir = os.path.dirname(os.path.realpath(__file__))
        self.setWindowIcon(QtGui.QIcon(scriptDir + os.path.sep + 'icon.png'))

        self.rooms_filename = scriptDir + os.path.sep + 'rooms.csv'
        self.clients_filename = scriptDir + os.path.sep + 'clients.csv'

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hata reservation"))
        self.roomprops.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.text_name.setText(_translate("MainWindow", "Имя*"))
        self.text_lastname.setText(_translate("MainWindow", "Фамилия*"))
        self.text_middlename.setText(_translate("MainWindow", "Отчество"))
        self.text_mobilenum.setText(_translate("MainWindow", "Номер телефона*"))
        self.text_datein.setText(_translate("MainWindow", "Дата въезда"))
        self.text_roomsnum.setText(_translate("MainWindow", "Количесво комнат"))
        self.text_hastv.setText(_translate("MainWindow", "Tv"))
        self.text_haswifi.setText(_translate("MainWindow", "Wi-Fi"))
        self.text_hassafe.setText(_translate("MainWindow", "Сейф"))
        self.text_haspets.setText(_translate("MainWindow", "Разрешены животные"))
        self.text_smoker.setText(_translate("MainWindow", "Для курящих"))
        self.text_hasbreakfast.setText(_translate("MainWindow", "Завтрак"))
        self.text_dateout.setText(_translate("MainWindow", "Дата выезда"))
        self.BtnSearch.setText(_translate("MainWindow", "Найти"))
        self.BtnReservate.setText(_translate("MainWindow", "Забронировать"))
