from PyQt5 import QtCore, QtGui, QtWidgets
import os

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.text = QtWidgets.QTextBrowser(self.centralwidget)
        self.text.setObjectName("text")
        self.gridLayout.addWidget(self.text, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnDo = QtWidgets.QPushButton(self.centralwidget)
        self.btnDo.setObjectName("btnDo")
        self.horizontalLayout.addWidget(self.btnDo)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_V = QtWidgets.QLabel(self.centralwidget)
        self.label_V.setObjectName("label_V")
        self.horizontalLayout_2.addWidget(self.label_V)
        self.line_V = QtWidgets.QLineEdit(self.centralwidget)
        self.line_V.setObjectName("line_V")
        self.horizontalLayout_2.addWidget(self.line_V)
        self.label_S = QtWidgets.QLabel(self.centralwidget)
        self.label_S.setObjectName("label_S")
        self.horizontalLayout_2.addWidget(self.label_S)
        self.line_S = QtWidgets.QLineEdit(self.centralwidget)
        self.line_S.setObjectName("line_S")
        self.horizontalLayout_2.addWidget(self.line_S)
        self.label_l = QtWidgets.QLabel(self.centralwidget)
        self.label_l.setObjectName("label_l")
        self.horizontalLayout_2.addWidget(self.label_l)
        self.line_l = QtWidgets.QLineEdit(self.centralwidget)
        self.line_l.setObjectName("line_l")
        self.horizontalLayout_2.addWidget(self.line_l)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_H = QtWidgets.QLabel(self.centralwidget)
        self.label_H.setObjectName("label_H")
        self.horizontalLayout_3.addWidget(self.label_H)
        self.line_H = QtWidgets.QLineEdit(self.centralwidget)
        self.line_H.setObjectName("line_H")
        self.horizontalLayout_3.addWidget(self.line_H)
        self.label_p1 = QtWidgets.QLabel(self.centralwidget)
        self.label_p1.setObjectName("label_p1")
        self.horizontalLayout_3.addWidget(self.label_p1)
        self.line_p1 = QtWidgets.QLineEdit(self.centralwidget)
        self.line_p1.setObjectName("line_p1")
        self.horizontalLayout_3.addWidget(self.line_p1)
        self.label_v = QtWidgets.QLabel(self.centralwidget)
        self.label_v.setObjectName("label_v")
        self.horizontalLayout_3.addWidget(self.label_v)
        self.line_v = QtWidgets.QLineEdit(self.centralwidget)
        self.line_v.setObjectName("line_v")
        self.horizontalLayout_3.addWidget(self.line_v)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        scriptDir = os.path.dirname(os.path.realpath(__file__))
        self.setWindowIcon(QtGui.QIcon(scriptDir + os.path.sep + 'icon.png'))

        self.filename = ''

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lab3"))
        self.btnDo.setText(_translate("MainWindow", "Сделать красиво"))
        self.label_V.setText(_translate("MainWindow", "V"))
        self.label_S.setText(_translate("MainWindow", "S сеч"))
        self.label_l.setText(_translate("MainWindow", "l"))
        self.label_H.setText(_translate("MainWindow", "H"))
        self.label_p1.setText(_translate("MainWindow", "p1"))
        self.label_v.setText(_translate("MainWindow", "v"))
