#include "CYLINDRICAL_SURFACE.h"
CYLINDRICAL_SURFACE::CYLINDRICAL_SURFACE() : AXIS2_PLACEMENT_3D_data(new AXIS2_PLACEMENT_3D), smth_d1(new double(NULL)), smth_d2(new double(NULL)) {}
CYLINDRICAL_SURFACE::~CYLINDRICAL_SURFACE()
{
	delete AXIS2_PLACEMENT_3D_data;
	delete smth_d1;
}